run:
  skip-dirs:
    - api/gen
    - broker/devices
  deadline: 10m

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-tags:
      - experimental
      - opinionated

  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15

linters:
  enable:
    - megacheck
    - govet
    - revive
    - misspell
    - depguard
    - gofmt
    - varcheck
    - gosimple
    - gocyclo
    - gocognit
    - gocritic
    - tparallel
    - unconvert
  fast: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  # print lines of code with issue, default is true
  print-issued-lines: true
  # print linter name in the end of issue text, default is true
  print-linter-name: true