name: Static-Code-Analisys
on:
  pull_request:
permissions:
  contents: read
jobs:
  golangci-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.0
          args: --config <(curl' https://github.com/golangci/golangci-lint/blob/master/.golangci.yml')
